name: Test and publish image

on:
  push:
    branches:
      - main

# See https://docs.github.com/en/actions/guides/publishing-docker-images for the
# theory, but we do some things differently.

jobs:
  test_image:
    name: Test static linking (using stable Rust)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # Run some fairly extensive tests to make sure that we actually produce
      # static, working programs.
      - name: Test image
        run: ./test-image

  build_and_push:
    name: Build image & push
    runs-on: ubuntu-latest

    needs:
      - test_image

    strategy:
      matrix:
        toolchain:
          - "stable"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: deltat/tch:latest
        

